{% set name = "neptune-tensorflow-keras" %}
{% set package_name = "neptune_tensorflow_keras" %}
{% set version = "2.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ package_name }}-{{ version }}.tar.gz
  sha256: b1c22e277e363888b7bc2778d73a86af193fb22ea439178822c70785b629faa7

build:
  noarch: python
  number: 1
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - neptune >=1.0.0
    - python >={{ python_min }}
    - tensorflow >=2,<3

test:
  imports:
    - neptune_tensorflow_keras
    - neptune_tensorflow_keras.impl
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with Tensorflow and Keras
  doc_url: https://github.com/neptune-ai/neptune-tensorflow-keras/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-tensorflow-keras

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - Raalsky
    - AleksanderWWW
    - PatrykGala
    - szysad
