{% set name = "neptune-tensorflow-keras" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neptune-ai/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 71cbdf43948d71e3ea9b32fcc38b88acbf18aa74f363941f26f504b05208a367

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - neptune-client >=0.9
    - python >=3.7
    - tensorflow >=2,<3

test:
  imports:
    - neptune_tensorflow_keras
    - neptune_tensorflow_keras.impl

about:
  home: https://neptune.ai/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Neptune Client integration with Tensorflow and Keras
  doc_url: https://github.com/neptune-ai/neptune-tensorflow-keras/blob/master/README.md
  dev_url: https://github.com/neptune-ai/neptune-tensorflow-keras

extra:
  recipe-maintainers:
    - aniezurawski
    - HubertJaworski
    - pitercl
    - Raalsky
    - shnela
